#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cached-property
Version  : 1.3.0
Release  : 4
URL      : https://github.com/pydanny/cached-property/archive/1.3.0.tar.gz
Source0  : https://github.com/pydanny/cached-property/archive/1.3.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cached-property-python3
Requires: cached-property-python
Requires: coverage
Requires: pytest
Requires: pytest-cov
Requires: wheel
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : tox
BuildRequires : virtualenv

%description
===============================
cached-property
===============================
.. image:: https://img.shields.io/pypi/v/cached-property.svg
:target: https://pypi.python.org/pypi/cached-property

%package python
Summary: python components for the cached-property package.
Group: Default
Requires: cached-property-python3

%description python
python components for the cached-property package.


%package python3
Summary: python3 components for the cached-property package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cached-property package.


%prep
%setup -q -n cached-property-1.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523050115
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
