#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cached-property
Version  : 1.5.1
Release  : 24
URL      : https://files.pythonhosted.org/packages/57/8e/0698e10350a57d46b3bcfe8eff1d4181642fd1724073336079cb13c5cf7f/cached-property-1.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/57/8e/0698e10350a57d46b3bcfe8eff1d4181642fd1724073336079cb13c5cf7f/cached-property-1.5.1.tar.gz
Summary  : A decorator for caching properties in classes.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cached-property-license = %{version}-%{release}
Requires: cached-property-python = %{version}-%{release}
Requires: cached-property-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
cached-property
        ===============================

%package license
Summary: license components for the cached-property package.
Group: Default

%description license
license components for the cached-property package.


%package python
Summary: python components for the cached-property package.
Group: Default
Requires: cached-property-python3 = %{version}-%{release}

%description python
python components for the cached-property package.


%package python3
Summary: python3 components for the cached-property package.
Group: Default
Requires: python3-core
Provides: pypi(cached_property)

%description python3
python3 components for the cached-property package.


%prep
%setup -q -n cached-property-1.5.1
cd %{_builddir}/cached-property-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583531764
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cached-property
cp %{_builddir}/cached-property-1.5.1/LICENSE %{buildroot}/usr/share/package-licenses/cached-property/2108a3483bc69d0ece9ef5a0993a4339b196e1a0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cached-property/2108a3483bc69d0ece9ef5a0993a4339b196e1a0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
