#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cached-property
Version  : 1.5.1
Release  : 20
URL      : https://files.pythonhosted.org/packages/57/8e/0698e10350a57d46b3bcfe8eff1d4181642fd1724073336079cb13c5cf7f/cached-property-1.5.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/57/8e/0698e10350a57d46b3bcfe8eff1d4181642fd1724073336079cb13c5cf7f/cached-property-1.5.1.tar.gz
Summary  : A decorator for caching properties in classes.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: cached-property-license = %{version}-%{release}
Requires: cached-property-python = %{version}-%{release}
Requires: cached-property-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
cached-property
        ===============================

%package license
Summary: license components for the cached-property package.
Group: Default

%description license
license components for the cached-property package.


%package python
Summary: python components for the cached-property package.
Group: Default
Requires: cached-property-python3 = %{version}-%{release}

%description python
python components for the cached-property package.


%package python3
Summary: python3 components for the cached-property package.
Group: Default
Requires: python3-core

%description python3
python3 components for the cached-property package.


%prep
%setup -q -n cached-property-1.5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546121780
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cached-property
cp LICENSE %{buildroot}/usr/share/package-licenses/cached-property/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cached-property/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
